# Dogfooding 'workon'
commands:
  install:
    - virtualenv env -p python3.6
    - . env/bin/activate
    - pip install -r requirements.txt
  activate:
    - . env/bin/activate
  test:
    - python test.py
  exit:
    - deactivate
